services:
  server:
    build:
      context: .
      dockerfile: src/cpp/Dockerfile.server
    volumes:
      - ./data:/usr/src/project/build/data
    container_name: server_container
    working_dir: /usr/src/project/build
    networks:
      - appnet

  client:
    build:
      context: ./src/python
      dockerfile: Dockerfile.client
    tty: true
    stdin_open: true
    init: true
    container_name: client_container
    working_dir: /usr/src/app
    entrypoint: ["python", "main.py"]
    networks:
      - appnet

networks:
  appnet:
    driver: bridge


