services:
  server:
    build:
      context: ./src/cpp_server
      dockerfile: Dockerfile.server
    volumes:
      - ./data:/usr/src/project/build/data
    ports:
      - "12345:12345"
    restart: always
    networks:
      appnet:
        ipv4_address: 172.28.0.2

  nodejs-server:
    build:
      context: ./src/nodejs_server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # חזרה לפורט 3000
    environment:
      - PORT=3000
    restart: always
    networks:
      - appnet

  react-client:
    build:
      context: ./src/react_client
      dockerfile: Dockerfile.react
    ports:
      - "3001:3001"  
    restart: always
    networks:
      - appnet
    #depends_on:
      #- nodejs-server
      #- server
  
networks:
  appnet:
    driver: bridge  
    ipam:
      config:
        - subnet: 172.28.0.0/16