version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
    restart: always

  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"   
    restart: always


    