version: '3.8'

services:
  server:
    build:
      context: ./src/cpp
      dockerfile: Dockerfile.server
    container_name: server
    networks:
      - appnet
    entrypoint: ["./server"]  

  client:
    build:
      context: ./src/python
      dockerfile: Dockerfile.client
    container_name: client
    depends_on:
      - server
    networks:
      - appnet
    entrypoint: ["python", "main.py"]  

networks:
  appnet:
    driver: bridge
