services:
  server:
    build:
      context: ./src/cpp_server
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
    restart: always

  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

    