FROM python:3.10-slim

# Set working directory inside the container
WORKDIR /usr/src/app

# Copy all client-related code into the container
COPY . ./

# Run the main script by default, arguments from docker-compose will be passed
ENTRYPOINT ["python3", "client.py"]
